// <auto-generated />
using System;
using FunlandV3.Areas.Customer.Data;
using FunlandV3.Areas.Customer.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunlandV3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240914101451_NEwPictures")]
    partial class NEwPictures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FunlandV3.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("AgeRestriction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBookingHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("PoolType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresSupervision")
                        .HasColumnType("bit");

                    b.HasKey("AmenityId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            AgeRestriction = "1-8",
                            Block = "Amenities Block",
                            ClosingTime = new TimeSpan(0, 20, 0, 0, 0),
                            ImageUrl = "/Images/SwimmingPool.jpg",
                            MaxBookingHours = 5,
                            Name = "Kids Pool",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            PoolType = "Kids",
                            RequiresSupervision = true
                        },
                        new
                        {
                            AmenityId = 2,
                            AgeRestriction = "9+",
                            Block = "Amenities Block",
                            ClosingTime = new TimeSpan(0, 20, 0, 0, 0),
                            ImageUrl = "/Images/KidsSwimmingPool.jpg",
                            MaxBookingHours = 5,
                            Name = "Adult Pool",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            PoolType = "Adult",
                            RequiresSupervision = true
                        });
                });

            modelBuilder.Entity("FunlandV3.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBookingHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Block = "Gaming Block",
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            ImageUrl = "/Images/LaserTag.jpg",
                            MaxBookingHours = 3,
                            Name = "Laser Tag",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            GameId = 2,
                            Block = "Gaming Block",
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            ImageUrl = "/Images/Bowling.png",
                            MaxBookingHours = 3,
                            Name = "Bowling",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("FunlandV3.Models.PartyRoom", b =>
                {
                    b.Property<int>("PartyRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyRoomId"));

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("PartyRoomId");

                    b.ToTable("PartyRooms");

                    b.HasData(
                        new
                        {
                            PartyRoomId = 1,
                            Block = "Party Block",
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Floor = 1,
                            ImageUrl = "/Images/PartyRoom1.jfif",
                            Name = "Room A",
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0),
                            RoomNumber = 1
                        },
                        new
                        {
                            PartyRoomId = 2,
                            Block = "Party Block",
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Floor = 1,
                            ImageUrl = "/Images/PartyRoom2.JPEG",
                            Name = "Room B",
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0),
                            RoomNumber = 2
                        },
                        new
                        {
                            PartyRoomId = 3,
                            Block = "Party Block",
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Floor = 2,
                            ImageUrl = "/Images/PartyRoom3.jpeg",
                            Name = "Room C",
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0),
                            RoomNumber = 1
                        },
                        new
                        {
                            PartyRoomId = 4,
                            Block = "Party Block",
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Floor = 2,
                            ImageUrl = "/Images/PartyRoom4.jfif",
                            Name = "Room D",
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0),
                            RoomNumber = 2
                        },
                        new
                        {
                            PartyRoomId = 5,
                            Block = "Party Block",
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Floor = 3,
                            ImageUrl = "/Images/PartyRoom5,jpg",
                            Name = "Room E",
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0),
                            RoomNumber = 1
                        },
                        new
                        {
                            PartyRoomId = 6,
                            Block = "Party Block",
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            Floor = 3,
                            ImageUrl = "/Images/PartyRoom6.JPEG",
                            Name = "Room F",
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0),
                            RoomNumber = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
